describe("Adding Tests to Form", function(){
    beforeEach(function(){
        cy.visit("http://localhost:3000/")
    })

    it("Tests Inputs on the Form", function(){
        cy.get('#pizzaButton')
          .click()
        cy.get('input[name="name"]')
          .type("Rodrigo")
          .should("have.value", "Rodrigo")
        // cy.get('input[name="email"]')
        //   .type("Rodrigo@rodrigo.com")
        //   .should("have.value", "Rodrigo@rodrigo.com")
        // cy.get('input[name="password"]')
        //   .type("Rodrigo")
        //   .should("have.value", "Rodrigo")
        cy.get('#size')
          .select("Large")
          .should("have.value", "Large")
        cy.get('input[name="pepperoni"]')
          .check()
          .should("be.checked")
        cy.get('input[name="sausage"]')
          .check()
          .should("be.checked")
        cy.get('input[name="chicken"]')
          .check()
          .should("be.checked")
        cy.get('input[name="mushrooms"]')
          .check()
          .should("be.checked")
        cy.get('textarea')
          .type("Rodrigo's Food")
          .should("have.value", "Rodrigo's Food")
        cy.get('button[type="submit"]')
          .click()
    })

    // it("Checks Form Validation Error Messages", function(){
    //     cy.get('input[name="name"]')
    //       .type("a")
    //       .type("{backspace}", { parseSpecialCharSequences: true })
    //     cy.get('#nameP')
    //       .should("be.visible")
    //     cy.get('input[name="email"]')
    //       .type("a")
    //       .should('have.length', 1)
    //     cy.get('#emailP')
    //       .should("be.visible")
    //     cy.get('input[name="password"]')
    //       .type("a")
    //       .type("{backspace}", { parseSpecialCharSequences: true })
    //     cy.get('#passwordP')
    //       .should("be.visible")
    //     cy.get('input[name="terms"]')
    //       .check()
    //       .uncheck()
    //     cy.get('#termsP')
    //       .should("be.visible")
    // })
})